#!/bin/bash
#
# /etc/init.d/bookshare
# Subsystem file for "bookshare" server
#
# chkconfig: 2345 95 05
# description: bookshare server daemon
#
# processname: bookshare
# config: /etc/sysconfig/mySystem
# pidfile: /var/run/bookshare.pid

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog="bookshare"
pidfile=/var/run/bookshare/${prog}.pid
lockfile=/var/lock/subsys/${prog}

start() {
    echo -n $"Starting $prog:"
    daemon --pidfile=${pidfile} /root/bookshare/bin/bookshare.sh
    RETVAL=$?
    [ "$RETVAL" = 0 ] && touch /var/lock/subsys/$prog
    echo
}

stop() {
    echo -n $"Stopping $prog:"
    killproc -p ${pidfile}
    RETVAL=$?
    [ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
    echo
}

reload() {
    echo -n $"Reloading $prog:"
    killproc $prog -HUP
    RETVAL=$?
    echo
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    reload)
        reload
        ;;
    condrestart)
        if [ -f /var/lock/subsys/$prog ] ; then
            stop
            # avoid race
            sleep 3
            start
        fi
        ;;
    status)
        status $prog
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|condrestart|status}"
        RETVAL=1
esac
exit $RETVAL

